# Generated by Django 3.1.3 on 2020-12-10 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('description', models.CharField(blank=True, max_length=400)),
                ('event_pic', models.ImageField(blank=True, upload_to='image/')),
                ('number', models.IntegerField()),
                ('address', models.CharField(blank=True, max_length=10)),
                ('event_date', models.CharField(max_length=10)),
                ('event_time', models.CharField(max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
