# Generated by Django 3.1.3 on 2020-11-29 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=400)),
                ('post_pic', models.ImageField(blank=True, upload_to='image/')),
                ('number', models.CharField(max_length=20)),
                ('rent_price', models.CharField(max_length=10)),
                ('sell_price', models.CharField(max_length=10)),
            ],
        ),
    ]
