export const newsApi  = 'https://5faaa726b5c645001602af7e.mockapi.io/api/v1/News'
export const boardgamesApi  ='https://5faaa726b5c645001602af7e.mockapi.io/api/v1/Boardgames'
export const searchApi  ='https://5faaa726b5c645001602af7e.mockapi.io/api/v1/Boardgames?name='
export const selectedApi  ='http://localhost:8000/api/v1/posts/profile/'
export const postListApi  ='http://localhost:8000/api/v1/posts/profile/list/'
export const selectedEventApi  = 'http://localhost:8000/api/v1/events/'
export const selectedPostApi  = 'http://localhost:8000/api/v1/posts/'
export const eventListApi  = 'http://localhost:8000/api/v1/events/list/'
export const commentsApi='http://localhost:8000/api/v1/events/comment/list/'
export const likeApi='http://localhost:8000/api/v1/events/like/list/'
export const createCommentApi='http://localhost:8000/api/v1/events/comment/create/'
export const createLikeApi='http://localhost:8000/api/v1/events/like/create/'
export const delLikeApi='http://localhost:8000/api/v1/events/like/'
export const commentsPostsApi='http://localhost:8000/api/v1/posts/comment/list/'
export const createCommentPostApi='http://localhost:8000/api/v1/posts/comment/create/'
export const participateApi='http://localhost:8000/api/v1/events/'
