# Generated by Django 3.1.3 on 2020-12-10 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='bio',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
    ]
