# Generated by Django 3.1.3 on 2020-12-11 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201211_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='postal',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(default='', max_length=500),
        ),
    ]
